version: '2'
services:
    1stopclick-mongodb:
        image: mongo:4.0.2
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/1stopClick/mongodb/:/data/db/
